"""
    Avantation REST Template

    TODO: Add Description  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pterodactyl_client
from pterodactyl_client.model.api_client_servers_server_id_files_copy_post_request import ApiClientServersServerIdFilesCopyPostRequest


class TestApiClientServersServerIdFilesCopyPostRequest(unittest.TestCase):
    """ApiClientServersServerIdFilesCopyPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiClientServersServerIdFilesCopyPostRequest(self):
        """Test ApiClientServersServerIdFilesCopyPostRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiClientServersServerIdFilesCopyPostRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
