"""
    Avantation REST Template

    TODO: Add Description  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import pterodactyl_client
from pterodactyl_client.api.server_database_api import ServerDatabaseApi  # noqa: E501


class TestServerDatabaseApi(unittest.TestCase):
    """ServerDatabaseApi unit test stubs"""

    def setUp(self):
        self.api = ServerDatabaseApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_application_servers_id_databases_get(self):
        """Test case for api_application_servers_id_databases_get

        """
        pass

    def test_api_application_servers_id_databases_id1_delete(self):
        """Test case for api_application_servers_id_databases_id1_delete

        """
        pass

    def test_api_application_servers_id_databases_id1_get(self):
        """Test case for api_application_servers_id_databases_id1_get

        """
        pass

    def test_api_application_servers_id_databases_id1_reset_password_post(self):
        """Test case for api_application_servers_id_databases_id1_reset_password_post

        """
        pass

    def test_api_application_servers_id_databases_post(self):
        """Test case for api_application_servers_id_databases_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
