"""
    Avantation REST Template

    TODO: Add Description  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pterodactyl_client
from pterodactyl_client.model.api_client_account_email_put_request import ApiClientAccountEmailPutRequest


class TestApiClientAccountEmailPutRequest(unittest.TestCase):
    """ApiClientAccountEmailPutRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiClientAccountEmailPutRequest(self):
        """Test ApiClientAccountEmailPutRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiClientAccountEmailPutRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
