"""
    Avantation REST Template

    TODO: Add Description  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pterodactyl_client
from pterodactyl_client.model.api_client_servers_server_id_files_rename_put_request_files_inner import ApiClientServersServerIdFilesRenamePutRequestFilesInner
globals()['ApiClientServersServerIdFilesRenamePutRequestFilesInner'] = ApiClientServersServerIdFilesRenamePutRequestFilesInner
from pterodactyl_client.model.api_client_servers_server_id_files_rename_put_request import ApiClientServersServerIdFilesRenamePutRequest


class TestApiClientServersServerIdFilesRenamePutRequest(unittest.TestCase):
    """ApiClientServersServerIdFilesRenamePutRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiClientServersServerIdFilesRenamePutRequest(self):
        """Test ApiClientServersServerIdFilesRenamePutRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiClientServersServerIdFilesRenamePutRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
