"""
    Avantation REST Template

    TODO: Add Description  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pterodactyl_client
from pterodactyl_client.model.api_client_account_api_keys_get_request import ApiClientAccountApiKeysGetRequest


class TestApiClientAccountApiKeysGetRequest(unittest.TestCase):
    """ApiClientAccountApiKeysGetRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiClientAccountApiKeysGetRequest(self):
        """Test ApiClientAccountApiKeysGetRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiClientAccountApiKeysGetRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
