"""
    Avantation REST Template

    TODO: Add Description  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import pterodactyl_client
from pterodactyl_client.api.server_api import ServerApi  # noqa: E501


class TestServerApi(unittest.TestCase):
    """ServerApi unit test stubs"""

    def setUp(self):
        self.api = ServerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_application_servers_external_remote_id1_get(self):
        """Test case for api_application_servers_external_remote_id1_get

        """
        pass

    def test_api_application_servers_get(self):
        """Test case for api_application_servers_get

        """
        pass

    def test_api_application_servers_id_delete(self):
        """Test case for api_application_servers_id_delete

        """
        pass

    def test_api_application_servers_id_force_delete(self):
        """Test case for api_application_servers_id_force_delete

        """
        pass

    def test_api_application_servers_id_get(self):
        """Test case for api_application_servers_id_get

        """
        pass

    def test_api_application_servers_id_reinstall_post(self):
        """Test case for api_application_servers_id_reinstall_post

        """
        pass

    def test_api_application_servers_id_suspend_post(self):
        """Test case for api_application_servers_id_suspend_post

        """
        pass

    def test_api_application_servers_id_unsuspend_post(self):
        """Test case for api_application_servers_id_unsuspend_post

        """
        pass

    def test_api_application_servers_post(self):
        """Test case for api_application_servers_post

        """
        pass

    def test_api_client_servers_server_id_backups_backup_id_delete(self):
        """Test case for api_client_servers_server_id_backups_backup_id_delete

        """
        pass

    def test_api_client_servers_server_id_backups_backup_id_download_get(self):
        """Test case for api_client_servers_server_id_backups_backup_id_download_get

        """
        pass

    def test_api_client_servers_server_id_backups_backup_id_get(self):
        """Test case for api_client_servers_server_id_backups_backup_id_get

        """
        pass

    def test_api_client_servers_server_id_backups_get(self):
        """Test case for api_client_servers_server_id_backups_get

        """
        pass

    def test_api_client_servers_server_id_backups_post(self):
        """Test case for api_client_servers_server_id_backups_post

        """
        pass

    def test_api_client_servers_server_id_command_post(self):
        """Test case for api_client_servers_server_id_command_post

        """
        pass

    def test_api_client_servers_server_id_databases_database_id_delete(self):
        """Test case for api_client_servers_server_id_databases_database_id_delete

        """
        pass

    def test_api_client_servers_server_id_databases_database_id_rotate_password_post(self):
        """Test case for api_client_servers_server_id_databases_database_id_rotate_password_post

        """
        pass

    def test_api_client_servers_server_id_databases_get(self):
        """Test case for api_client_servers_server_id_databases_get

        """
        pass

    def test_api_client_servers_server_id_databases_post(self):
        """Test case for api_client_servers_server_id_databases_post

        """
        pass

    def test_api_client_servers_server_id_files_compress_post(self):
        """Test case for api_client_servers_server_id_files_compress_post

        """
        pass

    def test_api_client_servers_server_id_files_contents_get(self):
        """Test case for api_client_servers_server_id_files_contents_get

        """
        pass

    def test_api_client_servers_server_id_files_copy_post(self):
        """Test case for api_client_servers_server_id_files_copy_post

        """
        pass

    def test_api_client_servers_server_id_files_create_folder_post(self):
        """Test case for api_client_servers_server_id_files_create_folder_post

        """
        pass

    def test_api_client_servers_server_id_files_decompress_post(self):
        """Test case for api_client_servers_server_id_files_decompress_post

        """
        pass

    def test_api_client_servers_server_id_files_delete_post(self):
        """Test case for api_client_servers_server_id_files_delete_post

        """
        pass

    def test_api_client_servers_server_id_files_download_get(self):
        """Test case for api_client_servers_server_id_files_download_get

        """
        pass

    def test_api_client_servers_server_id_files_list_get(self):
        """Test case for api_client_servers_server_id_files_list_get

        """
        pass

    def test_api_client_servers_server_id_files_rename_put(self):
        """Test case for api_client_servers_server_id_files_rename_put

        """
        pass

    def test_api_client_servers_server_id_files_upload_get(self):
        """Test case for api_client_servers_server_id_files_upload_get

        """
        pass

    def test_api_client_servers_server_id_files_write_post(self):
        """Test case for api_client_servers_server_id_files_write_post

        """
        pass

    def test_api_client_servers_server_id_get(self):
        """Test case for api_client_servers_server_id_get

        """
        pass

    def test_api_client_servers_server_id_network_allocations_get(self):
        """Test case for api_client_servers_server_id_network_allocations_get

        """
        pass

    def test_api_client_servers_server_id_network_allocations_id_delete(self):
        """Test case for api_client_servers_server_id_network_allocations_id_delete

        """
        pass

    def test_api_client_servers_server_id_network_allocations_id_post(self):
        """Test case for api_client_servers_server_id_network_allocations_id_post

        """
        pass

    def test_api_client_servers_server_id_network_allocations_id_primary_post(self):
        """Test case for api_client_servers_server_id_network_allocations_id_primary_post

        """
        pass

    def test_api_client_servers_server_id_network_allocations_post(self):
        """Test case for api_client_servers_server_id_network_allocations_post

        """
        pass

    def test_api_client_servers_server_id_power_post(self):
        """Test case for api_client_servers_server_id_power_post

        """
        pass

    def test_api_client_servers_server_id_resources_get(self):
        """Test case for api_client_servers_server_id_resources_get

        """
        pass

    def test_api_client_servers_server_id_schedules_get(self):
        """Test case for api_client_servers_server_id_schedules_get

        """
        pass

    def test_api_client_servers_server_id_schedules_id_delete(self):
        """Test case for api_client_servers_server_id_schedules_id_delete

        """
        pass

    def test_api_client_servers_server_id_schedules_id_get(self):
        """Test case for api_client_servers_server_id_schedules_id_get

        """
        pass

    def test_api_client_servers_server_id_schedules_id_post(self):
        """Test case for api_client_servers_server_id_schedules_id_post

        """
        pass

    def test_api_client_servers_server_id_schedules_id_tasks_id1_delete(self):
        """Test case for api_client_servers_server_id_schedules_id_tasks_id1_delete

        """
        pass

    def test_api_client_servers_server_id_schedules_id_tasks_id1_post(self):
        """Test case for api_client_servers_server_id_schedules_id_tasks_id1_post

        """
        pass

    def test_api_client_servers_server_id_schedules_id_tasks_post(self):
        """Test case for api_client_servers_server_id_schedules_id_tasks_post

        """
        pass

    def test_api_client_servers_server_id_schedules_post(self):
        """Test case for api_client_servers_server_id_schedules_post

        """
        pass

    def test_api_client_servers_server_id_settings_reinstall_post(self):
        """Test case for api_client_servers_server_id_settings_reinstall_post

        """
        pass

    def test_api_client_servers_server_id_settings_rename_post(self):
        """Test case for api_client_servers_server_id_settings_rename_post

        """
        pass

    def test_api_client_servers_server_id_startup_get(self):
        """Test case for api_client_servers_server_id_startup_get

        """
        pass

    def test_api_client_servers_server_id_startup_variable_put(self):
        """Test case for api_client_servers_server_id_startup_variable_put

        """
        pass

    def test_api_client_servers_server_id_users_get(self):
        """Test case for api_client_servers_server_id_users_get

        """
        pass

    def test_api_client_servers_server_id_users_post(self):
        """Test case for api_client_servers_server_id_users_post

        """
        pass

    def test_api_client_servers_server_id_users_user_id_delete(self):
        """Test case for api_client_servers_server_id_users_user_id_delete

        """
        pass

    def test_api_client_servers_server_id_users_user_id_get(self):
        """Test case for api_client_servers_server_id_users_user_id_get

        """
        pass

    def test_api_client_servers_server_id_users_user_id_post(self):
        """Test case for api_client_servers_server_id_users_user_id_post

        """
        pass

    def test_api_client_servers_server_id_websocket_get(self):
        """Test case for api_client_servers_server_id_websocket_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
