"""
    Avantation REST Template

    TODO: Add Description  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pterodactyl_client
from pterodactyl_client.model.api_application_servers_get_request_environment import ApiApplicationServersGetRequestEnvironment


class TestApiApplicationServersGetRequestEnvironment(unittest.TestCase):
    """ApiApplicationServersGetRequestEnvironment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiApplicationServersGetRequestEnvironment(self):
        """Test ApiApplicationServersGetRequestEnvironment"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiApplicationServersGetRequestEnvironment()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
