"""
    Avantation REST Template

    TODO: Add Description  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import pterodactyl_client
from pterodactyl_client.api.account_api import AccountApi  # noqa: E501


class TestAccountApi(unittest.TestCase):
    """AccountApi unit test stubs"""

    def setUp(self):
        self.api = AccountApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_client_account_api_keys_get(self):
        """Test case for api_client_account_api_keys_get

        """
        pass

    def test_api_client_account_api_keys_key_id_delete(self):
        """Test case for api_client_account_api_keys_key_id_delete

        """
        pass

    def test_api_client_account_api_keys_post(self):
        """Test case for api_client_account_api_keys_post

        """
        pass

    def test_api_client_account_email_put(self):
        """Test case for api_client_account_email_put

        """
        pass

    def test_api_client_account_get(self):
        """Test case for api_client_account_get

        """
        pass

    def test_api_client_account_password_put(self):
        """Test case for api_client_account_password_put

        """
        pass

    def test_api_client_account_two_factor_delete(self):
        """Test case for api_client_account_two_factor_delete

        """
        pass

    def test_api_client_account_two_factor_get(self):
        """Test case for api_client_account_two_factor_get

        """
        pass

    def test_api_client_account_two_factor_post(self):
        """Test case for api_client_account_two_factor_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
