"""
    Avantation REST Template

    TODO: Add Description  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pterodactyl_client
from pterodactyl_client.model.api_application_servers_id_databases_get_request import ApiApplicationServersIdDatabasesGetRequest


class TestApiApplicationServersIdDatabasesGetRequest(unittest.TestCase):
    """ApiApplicationServersIdDatabasesGetRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiApplicationServersIdDatabasesGetRequest(self):
        """Test ApiApplicationServersIdDatabasesGetRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiApplicationServersIdDatabasesGetRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
