"""
    Avantation REST Template

    TODO: Add Description  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import pterodactyl_client
from pterodactyl_client.api.users_api import UsersApi  # noqa: E501


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self):
        self.api = UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_application_users_external_remote_id_get(self):
        """Test case for api_application_users_external_remote_id_get

        """
        pass

    def test_api_application_users_get(self):
        """Test case for api_application_users_get

        """
        pass

    def test_api_application_users_id_delete(self):
        """Test case for api_application_users_id_delete

        """
        pass

    def test_api_application_users_id_get(self):
        """Test case for api_application_users_id_get

        """
        pass

    def test_api_application_users_post(self):
        """Test case for api_application_users_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
