"""
    Avantation REST Template

    TODO: Add Description  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pterodactyl_client
from pterodactyl_client.model.api_client_servers_server_id_schedules_id_delete_request import ApiClientServersServerIdSchedulesIdDeleteRequest


class TestApiClientServersServerIdSchedulesIdDeleteRequest(unittest.TestCase):
    """ApiClientServersServerIdSchedulesIdDeleteRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiClientServersServerIdSchedulesIdDeleteRequest(self):
        """Test ApiClientServersServerIdSchedulesIdDeleteRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiClientServersServerIdSchedulesIdDeleteRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
