"""
    Avantation REST Template

    TODO: Add Description  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import pterodactyl_client
from pterodactyl_client.api.locations_api import LocationsApi  # noqa: E501


class TestLocationsApi(unittest.TestCase):
    """LocationsApi unit test stubs"""

    def setUp(self):
        self.api = LocationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_application_locations_get(self):
        """Test case for api_application_locations_get

        """
        pass

    def test_api_application_locations_id_delete(self):
        """Test case for api_application_locations_id_delete

        """
        pass

    def test_api_application_locations_id_get(self):
        """Test case for api_application_locations_id_get

        """
        pass

    def test_api_application_locations_post(self):
        """Test case for api_application_locations_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
