"""
    Avantation REST Template

    TODO: Add Description  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pterodactyl_client
from pterodactyl_client.model.api_application_nodes_id_allocations_get_request import ApiApplicationNodesIdAllocationsGetRequest


class TestApiApplicationNodesIdAllocationsGetRequest(unittest.TestCase):
    """ApiApplicationNodesIdAllocationsGetRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiApplicationNodesIdAllocationsGetRequest(self):
        """Test ApiApplicationNodesIdAllocationsGetRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiApplicationNodesIdAllocationsGetRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
