"""
    Avantation REST Template

    TODO: Add Description  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import pterodactyl_client
from pterodactyl_client.api.client_api import ClientApi  # noqa: E501


class TestClientApi(unittest.TestCase):
    """ClientApi unit test stubs"""

    def setUp(self):
        self.api = ClientApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_client_get(self):
        """Test case for api_client_get

        """
        pass

    def test_api_client_permissions_get(self):
        """Test case for api_client_permissions_get

        """
        pass

    def test_api_client_servers_server_id_command_post(self):
        """Test case for api_client_servers_server_id_command_post

        """
        pass

    def test_api_client_servers_server_id_databases_get(self):
        """Test case for api_client_servers_server_id_databases_get

        """
        pass

    def test_api_client_servers_server_id_databases_post(self):
        """Test case for api_client_servers_server_id_databases_post

        """
        pass

    def test_api_client_servers_server_id_get(self):
        """Test case for api_client_servers_server_id_get

        """
        pass

    def test_api_client_servers_server_id_power_post(self):
        """Test case for api_client_servers_server_id_power_post

        """
        pass

    def test_api_client_servers_server_id_resources_get(self):
        """Test case for api_client_servers_server_id_resources_get

        """
        pass

    def test_api_client_servers_server_id_startup_get(self):
        """Test case for api_client_servers_server_id_startup_get

        """
        pass

    def test_api_client_servers_server_id_websocket_get(self):
        """Test case for api_client_servers_server_id_websocket_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
