# flake8: noqa

# import all models into this package
# if you have many models here with many references from one model to another this may
# raise a RecursionError
# to avoid this, import only the models that you directly need like:
# from from pterodactyl_client.model.pet import Pet
# or import this package, but before doing it, use:
# import sys
# sys.setrecursionlimit(n)

from pterodactyl_client.model.account_api_keys_post_request import AccountApiKeysPostRequest
from pterodactyl_client.model.account_email_put_request import AccountEmailPutRequest
from pterodactyl_client.model.account_password_put_request import AccountPasswordPutRequest
from pterodactyl_client.model.account_two_factor_post_request import AccountTwoFactorPostRequest
from pterodactyl_client.model.allocationsallocation_setallocationnote_request import AllocationsallocationSetallocationnoteRequest
from pterodactyl_client.model.api_keys_create_ap_ikey_request import ApiKeysCreateAPIkeyRequest
from pterodactyl_client.model.application_locations_location_id_patch_request import ApplicationLocationsLocationIdPatchRequest
from pterodactyl_client.model.application_locations_post_request import ApplicationLocationsPostRequest
from pterodactyl_client.model.application_nodes_node_id_allocations_post_request import ApplicationNodesNodeIdAllocationsPostRequest
from pterodactyl_client.model.application_nodes_node_id_patch_request import ApplicationNodesNodeIdPatchRequest
from pterodactyl_client.model.application_nodes_post_request import ApplicationNodesPostRequest
from pterodactyl_client.model.application_servers_post_request import ApplicationServersPostRequest
from pterodactyl_client.model.application_servers_server_id_build_patch_request import ApplicationServersServerIdBuildPatchRequest
from pterodactyl_client.model.application_servers_server_id_databases_post_request import ApplicationServersServerIdDatabasesPostRequest
from pterodactyl_client.model.application_servers_server_id_details_patch_request import ApplicationServersServerIdDetailsPatchRequest
from pterodactyl_client.model.application_servers_server_id_startup_patch_request import ApplicationServersServerIdStartupPatchRequest
from pterodactyl_client.model.application_users_post_request import ApplicationUsersPostRequest
from pterodactyl_client.model.application_users_user_id_patch_request import ApplicationUsersUserIdPatchRequest
from pterodactyl_client.model.client_servers_server_id_command_post_request import ClientServersServerIdCommandPostRequest
from pterodactyl_client.model.client_servers_server_id_databases_post_request import ClientServersServerIdDatabasesPostRequest
from pterodactyl_client.model.client_servers_server_id_files_compress_post_request import ClientServersServerIdFilesCompressPostRequest
from pterodactyl_client.model.client_servers_server_id_files_copy_post_request import ClientServersServerIdFilesCopyPostRequest
from pterodactyl_client.model.client_servers_server_id_files_create_folder_post_request import ClientServersServerIdFilesCreateFolderPostRequest
from pterodactyl_client.model.client_servers_server_id_files_decompress_post_request import ClientServersServerIdFilesDecompressPostRequest
from pterodactyl_client.model.client_servers_server_id_files_delete_post_request import ClientServersServerIdFilesDeletePostRequest
from pterodactyl_client.model.client_servers_server_id_files_rename_put_request import ClientServersServerIdFilesRenamePutRequest
from pterodactyl_client.model.client_servers_server_id_network_allocations_allocation_id_post_request import ClientServersServerIdNetworkAllocationsAllocationIdPostRequest
from pterodactyl_client.model.client_servers_server_id_power_post_request import ClientServersServerIdPowerPostRequest
from pterodactyl_client.model.client_servers_server_id_schedules_post_request import ClientServersServerIdSchedulesPostRequest
from pterodactyl_client.model.client_servers_server_id_schedules_schedule_id_post_request import ClientServersServerIdSchedulesScheduleIdPostRequest
from pterodactyl_client.model.client_servers_server_id_schedules_schedule_id_tasks_post_request import ClientServersServerIdSchedulesScheduleIdTasksPostRequest
from pterodactyl_client.model.client_servers_server_id_schedules_schedule_id_tasks_task_id_post_request import ClientServersServerIdSchedulesScheduleIdTasksTaskIdPostRequest
from pterodactyl_client.model.client_servers_server_id_settings_rename_post_request import ClientServersServerIdSettingsRenamePostRequest
from pterodactyl_client.model.client_servers_server_id_startup_variable_put_request import ClientServersServerIdStartupVariablePutRequest
from pterodactyl_client.model.client_servers_server_id_users_post_request import ClientServersServerIdUsersPostRequest
from pterodactyl_client.model.client_servers_server_id_users_user_id_post_request import ClientServersServerIdUsersUserIdPostRequest
from pterodactyl_client.model.command_sendcommand_request import CommandSendcommandRequest
from pterodactyl_client.model.compress_compressfile_request import CompressCompressfileRequest
from pterodactyl_client.model.copy_copyfile_request import CopyCopyfileRequest
from pterodactyl_client.model.create_folder_createfolder_request import CreateFolderCreatefolderRequest
from pterodactyl_client.model.create_user_request1 import CreateUserRequest1
from pterodactyl_client.model.createallocations_request import CreateallocationsRequest
from pterodactyl_client.model.createdatabase_request import CreatedatabaseRequest
from pterodactyl_client.model.createdatabase_request1 import CreatedatabaseRequest1
from pterodactyl_client.model.createlocation_request import CreatelocationRequest
from pterodactyl_client.model.createnode_request import CreatenodeRequest
from pterodactyl_client.model.createschedule_request import CreatescheduleRequest
from pterodactyl_client.model.createserver_request import CreateserverRequest
from pterodactyl_client.model.createuser_request import CreateuserRequest
from pterodactyl_client.model.decompress_decompressfile_request import DecompressDecompressfileRequest
from pterodactyl_client.model.delete_deletefile_request import DeleteDeletefileRequest
from pterodactyl_client.model.email_updateemail_request import EmailUpdateemailRequest
from pterodactyl_client.model.node_updatenode_request import NodeUpdatenodeRequest
from pterodactyl_client.model.password_updatepassword_request import PasswordUpdatepasswordRequest
from pterodactyl_client.model.power_changepowerstate_request import PowerChangepowerstateRequest
from pterodactyl_client.model.rename_renamefile_request import RenameRenamefileRequest
from pterodactyl_client.model.rename_renameserver_request import RenameRenameserverRequest
from pterodactyl_client.model.schedule_updateschedule_request import ScheduleUpdatescheduleRequest
from pterodactyl_client.model.scheduletasks_createtask_request import ScheduletasksCreatetaskRequest
from pterodactyl_client.model.scheduletaskstask_updatetask_request import ScheduletaskstaskUpdatetaskRequest
from pterodactyl_client.model.serverbuild_updatebuild_request import ServerbuildUpdatebuildRequest
from pterodactyl_client.model.serverdetails_updatedetails_request import ServerdetailsUpdatedetailsRequest
from pterodactyl_client.model.serverstartup_updatestartup_request import ServerstartupUpdatestartupRequest
from pterodactyl_client.model.subuser_updateuser_request import SubuserUpdateuserRequest
from pterodactyl_client.model.two_factor_disable2_fa_request import TwoFactorDisable2FARequest
from pterodactyl_client.model.two_factor_enable2_fa_request import TwoFactorEnable2FARequest
from pterodactyl_client.model.updatelocation_request import UpdatelocationRequest
from pterodactyl_client.model.updateuser_request import UpdateuserRequest
from pterodactyl_client.model.variable_update_variable_request import VariableUpdateVariableRequest
