# flake8: noqa

# import all models into this package
# if you have many models here with many references from one model to another this may
# raise a RecursionError
# to avoid this, import only the models that you directly need like:
# from from pterodactyl_client.model.pet import Pet
# or import this package, but before doing it, use:
# import sys
# sys.setrecursionlimit(n)

from pterodactyl_client.model.allocations_allocation_setallocationnote_request import AllocationsAllocationSetallocationnoteRequest
from pterodactyl_client.model.allocationsallocation_setallocationnote_request import AllocationsallocationSetallocationnoteRequest
from pterodactyl_client.model.api_keys_create_ap_ikey_request import ApiKeysCreateAPIkeyRequest
from pterodactyl_client.model.command_sendcommand_request import CommandSendcommandRequest
from pterodactyl_client.model.compress_compressfile_request import CompressCompressfileRequest
from pterodactyl_client.model.copy_copyfile_request import CopyCopyfileRequest
from pterodactyl_client.model.create_folder_createfolder_request import CreateFolderCreatefolderRequest
from pterodactyl_client.model.create_user1_request import CreateUser1Request
from pterodactyl_client.model.create_user_request1 import CreateUserRequest1
from pterodactyl_client.model.createallocations_request import CreateallocationsRequest
from pterodactyl_client.model.createdatabase_request import CreatedatabaseRequest
from pterodactyl_client.model.createdatabase_request1 import CreatedatabaseRequest1
from pterodactyl_client.model.createlocation_request import CreatelocationRequest
from pterodactyl_client.model.createnode_request import CreatenodeRequest
from pterodactyl_client.model.createschedule_request import CreatescheduleRequest
from pterodactyl_client.model.createserver_request import CreateserverRequest
from pterodactyl_client.model.createuser_request import CreateuserRequest
from pterodactyl_client.model.decompress_decompressfile_request import DecompressDecompressfileRequest
from pterodactyl_client.model.delete_deletefile_request import DeleteDeletefileRequest
from pterodactyl_client.model.email_updateemail_request import EmailUpdateemailRequest
from pterodactyl_client.model.node_updatenode_request import NodeUpdatenodeRequest
from pterodactyl_client.model.password_updatepassword_request import PasswordUpdatepasswordRequest
from pterodactyl_client.model.post_createdatabase_request import PostCreatedatabaseRequest
from pterodactyl_client.model.power_changepowerstate_request import PowerChangepowerstateRequest
from pterodactyl_client.model.rename_renamefile_request import RenameRenamefileRequest
from pterodactyl_client.model.rename_renameserver_request import RenameRenameserverRequest
from pterodactyl_client.model.schedule_tasks_createtask_request import ScheduleTasksCreatetaskRequest
from pterodactyl_client.model.schedule_tasks_task_updatetask_request import ScheduleTasksTaskUpdatetaskRequest
from pterodactyl_client.model.schedule_updateschedule_request import ScheduleUpdatescheduleRequest
from pterodactyl_client.model.scheduletasks_createtask_request import ScheduletasksCreatetaskRequest
from pterodactyl_client.model.scheduletaskstask_updatetask_request import ScheduletaskstaskUpdatetaskRequest
from pterodactyl_client.model.server_build_updatebuild_request import ServerBuildUpdatebuildRequest
from pterodactyl_client.model.server_details_updatedetails_request import ServerDetailsUpdatedetailsRequest
from pterodactyl_client.model.server_startup_updatestartup_request import ServerStartupUpdatestartupRequest
from pterodactyl_client.model.serverbuild_updatebuild_request import ServerbuildUpdatebuildRequest
from pterodactyl_client.model.serverdetails_updatedetails_request import ServerdetailsUpdatedetailsRequest
from pterodactyl_client.model.serverstartup_updatestartup_request import ServerstartupUpdatestartupRequest
from pterodactyl_client.model.subuser_updateuser_request import SubuserUpdateuserRequest
from pterodactyl_client.model.two_factor_disable2_fa_request import TwoFactorDisable2FARequest
from pterodactyl_client.model.two_factor_enable2_fa_request import TwoFactorEnable2FARequest
from pterodactyl_client.model.updatelocation_request import UpdatelocationRequest
from pterodactyl_client.model.updateuser_request import UpdateuserRequest
from pterodactyl_client.model.variable_update_variable_request import VariableUpdateVariableRequest
