# flake8: noqa

"""
    Avantation REST Template

    TODO: Add Description  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from pterodactyl_client.api_client import ApiClient

# import Configuration
from pterodactyl_client.configuration import Configuration

# import exceptions
from pterodactyl_client.exceptions import OpenApiException
from pterodactyl_client.exceptions import ApiAttributeError
from pterodactyl_client.exceptions import ApiTypeError
from pterodactyl_client.exceptions import ApiValueError
from pterodactyl_client.exceptions import ApiKeyError
from pterodactyl_client.exceptions import ApiException
